### ISSUE TITLE
undefined reference to symbol 'deflate' FIX

### ISSUE THREAD

**Issue by ssuffian** [djcsdy/swfmill#37]
After fixing the other bug regarding the freetype include error, I still received an error when doing 'make'. This seemed to fix it:

/usr/bin/ld: swft/swfmill-swft_import_png.o: undefined reference to symbol 'deflate'
/lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line

To fix this problem, in src/MakeFile:
On line 160 add the following links: ' -lm -lz -lcrypt'

So line 160 initially looks like this:
EXSLT_LIBS = -lexslt -lxslt -lxml2

and after adding links it looks like this:
EXSLT_LIBS = -lexslt -lxslt -lxml2  -lm -lz -lcrypt 

This change allowed me to make and make install and use the code.

Line:

**Comment by djcsdy** [comment]
This is fixed as of ecc04cfbd658d24ffd7de67d34963b2ee1aafb36. The fix will be included in swfmill 0.3.5.

The problem was that the dynamic linking policy has changed in recent versions of GNU ld. Transitive dependencies used to be linked automatically, but now they must be linked explicitly. swfmill depends on libpng, and libpng depends on zlib, so now swfmill must explicitly link zlib.
