### ISSUE TITLE
SWFmill command line will not stay open

### ISSUE THREAD

**Issue by ReluctantSniper** [djcsdy/swfmill#44]
I'm clearly out of my depth here, but if I run SWFmill.exe with any and all compatibility settings, it will not stay open. I see a flash of the command line, then it closes.

**Comment by djcsdy** [comment]
That’s not how a command line tool works. You need to open up a command prompt, and run swfmill from inside the command prompt. You don’t need to have any compatibility settings turned on, and in fact if you have set some compatibility settings you should turn them off again.

In Windows you can either use the old “Command Prompt” (`cmd.exe`), or Windows PowerShell. If you have no prior knowledge of either, then I would suggest starting with Windows PowerShell, although the basics are the same in both tools.

Both Command Prompt and Windows PowerShell can be found in the start menu, for example by clicking the start button (or the search button) and typing the name of the tool.

Once you have a command line open you need to navigate to wherever you extracted swfmill and run it. For example if you extracted swfmill into a "swfmill" folder in your "Documents" folder:

```
cd Documents\swfmill
swfmill
```

This will print the help text to the console. To extract a SWF to XML you would type something like:

```
swfmill swf2xml movie.swf movie.xml
```

Where `movie.swf` is the movie you want to extract, and `movie.xml` is the name of the output file. In this example `movie.swf` would need to be placed in the same folder as swfmill.exe, and `movie.xml` would be written out into the same folder.

Hopefully that gets you started. You can find tutorials on using Command Prompt or PowerShell all over the Internet. I’m afraid I don’t know a particular tutorial to recommend.

If you’re going to be using swfmill a lot then you probably will want to [edit your System Path](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/) to include swfmill. Then you won’t need to navigate folders every time you want to use it.

I don’t want to discourage you but I think it’s fair to warn you that swfmill is not very well documented and assumes a lot of prior knowledge. Partially this is just due to the nature of the tool and partially it is because swfmill was never really polished up and finished, and it’s kind of obsolete now that Flash is disappearing from the Internet. If you don’t have a lot of technical background you might find that this tool is one of the most difficult places to start learning. Sorry about that.

If your interest in swfmill is commercial then you and/or your employer might be interested to know that I am available for consultancy work via my business [Software Ventures Limited](http://softwareventures.uk/).

HTH :-).
